# Generated by Django 5.0.7 on 2025-08-28 09:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_prompt",
                    models.TextField(
                        help_text="User's original prompt for story generation",
                        max_length=1000,
                    ),
                ),
                (
                    "story",
                    models.TextField(
                        blank=True, help_text="Generated story content", null=True
                    ),
                ),
                (
                    "character_description",
                    models.TextField(
                        blank=True,
                        help_text="Generated character description",
                        null=True,
                    ),
                ),
                (
                    "character_image",
                    models.CharField(
                        blank=True,
                        help_text="Filename of generated character image",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "background_image",
                    models.CharField(
                        blank=True,
                        help_text="Filename of generated background image",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "combined_image",
                    models.CharField(
                        blank=True,
                        help_text="Filename of final combined scene image",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if generation failed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this story (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Generation",
                "verbose_name_plural": "Story Generations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AudioUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        help_text="Uploaded audio file for transcription",
                        upload_to="audio_uploads/",
                    ),
                ),
                (
                    "transcribed_text",
                    models.TextField(
                        blank=True, help_text="Transcribed text from audio", null=True
                    ),
                ),
                (
                    "transcription_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "story_generation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_upload",
                        to="story_app.storygeneration",
                    ),
                ),
            ],
        ),
    ]
